.PHONY: clean All

All:
	@echo "----------Building project:[ myvector - Debug ]----------"
	@cd "myvector" && "$(MAKE)" -f  "myvector.mk"
clean:
	@echo "----------Cleaning project:[ myvector - Debug ]----------"
	@cd "myvector" && "$(MAKE)" -f  "myvector.mk" clean
