.PHONY: clean All

All:
	@echo "----------Building project:[ ssh_sockets - Debug ]----------"
	@cd "ssh_sockets" && "$(MAKE)" -f  "ssh_sockets.mk"
clean:
	@echo "----------Cleaning project:[ ssh_sockets - Debug ]----------"
	@cd "ssh_sockets" && "$(MAKE)" -f  "ssh_sockets.mk" clean
